packages:
  onju_voice: !include onju-voice.yaml

substitutions:
  name: onju-voice-test
  friendly_name: Onju Voice Test

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: XwRsRj336SoAv5if5YaME1RT9gGpO1gJGEBU/q8oNvQ=

wifi:
  ssid: "test"
  password: "test1234"
